app:
  name: vixar-processor
  image:
    name: daronenko/vixar-processor
    tag: 0839865b
  clients:
    llm:
      url: "http://sntmnt:9999"
      timeout: 1m
  processor:
    workers_count: 2
    max_retries: 2
    retry_delay: 10s
  postgres:
    host: postgres
    port: 5432
  smtp:
    host: smtp.mail.ru
    port: 587
  kafka:
    hostname: kafka
    port: 9093
    group_id: vixar_processor
    topics:
      scraper_data: scraper_data
      notifications: notifications
