app:
  name: vixar-processor
  image:
    name: daronenko/vixar-processor
    tag: 192698e8
  clients:
    llm:
      url: "http://sntmnt:9999"
      timeout: 1m
  processor:
    workers_count: 2
    max_retries: 2
    retry_delay: 10s
  postgres:
    host: postgres
    port: 5432
  kafka:
    hostname: kafka
    port: 9093
    group_id: vixar_processor
    topic: scraper_data
