app:
  name: vixar-scheduler
  image:
    name: daronenko/vixar-scheduler
    tag: 8540d142
  scheduler:
    cron_pattern: "15 00 * * *"
    workers_count: 2
  scraper:
    output_every: 10000
    log_errors: false
    max_depth: 1
    filter_pattern: "^[A-Za-zА-Яа-яЁё]+$"
    tags_to_parse: ["div", "span", "p", "a", "h1", "h2", "h3", "h4", "h5", "h6"]
    is_async: false
    # async_delay: 3s
    # async_request_limit: 5
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
    headers:
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      accept_language: "en-US,en;q=0.9"
      accept_encoding: "gzip, deflate, br, zstd"
      connection: "keep-alive"
    queue:
      enabled: true
      thread_number: 5
      max_size: 250000
  system_server:
    enabled: true
    port: 8811
  kafka:
    max_retry: 5
    brokers:
      - kafka:9093
    topic: scraper_data
