app:
  name: vixarapi
  image:
    name: daronenko/vixarapi
    tag: 192698e8
  cookie:
    session:
      name: "session_id"
      expiration: 4320h
  http:
    port: "8000"
  cors:
    allow_origins: ["https://vixar.tech"]
    allow_credentials: true
    max_age: 24h
  scheduler:
    refresh_search_table_pattern: "15 03 * * *"
  vk:
    http:
      timeout: 5s
    auth:
      url: "https://id.vk.ru"
      client_id: "54390662"
  postgres:
    host: postgres
    port: 5432
  redis:
    addr: redis:6379
    db: 0
