app:
  name: vixarapi
  image:
    name: daronenko/vixarapi
    tag: d42ce97d
  http:
    port: "8000"
  cors:
    allow_origins: ["https://vixar.tech"]
    allow_credentials: true
    max_age: 24h
  scheduler:
    refresh_search_table_pattern: "15 03 * * *"
  postgres:
    host: postgres
    port: 5432
